# This file is part of "∂DIBR", a differentiable renderer based on Depth Image Based Rendering (DIBR) techniques for fast Novel View Synthesis.
# Copyright (C) 2026 "Université Libre de Bruxelles (ULB)". All rights reserved.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# Contact:
#     - Armand Losfeld - armand.lfd.pro@proton.me
#     - Daniele Bonatto - daniele.bonatto@ulb.be


[DiffDIBR.quality]
threshold = 0.20

[DiffDIBR.quality.foreground]
scale = 1.0
power = 1.0

[DiffDIBR.quality.side]
scale = 2.0
power = 1.0

[DiffDIBR.quality.shape]
scale = 0.0
power = 1.0

[DiffDIBR.quality.depth]
scale = 0.0
power = 3.0

[DiffDIBR.quality.normal]
scale = 0.1
power = 1.0

[DiffDIBR.quality.face_camera]
scale = 0.0
power = 2.0

[DiffDIBR.blending]
method = "Masked"
default_t4_color = [0.5, 0.5, 0.5, 0]
default_t1_color = [0.95, ]